### ISSUE TITLE
Question about meeting state

### ISSUE THREAD

**Issue by chrome** [bluejeans/api-rest-meetings#4]
Hey there!

I have a couple questions related to REST API. 

I'm trying to determine in which state meeting present at current moment.

To do so I making a query to `GET /v1/user/{user_id}/live_meetings/{numeric_meeting_id}`.
If there is an answer — it means that meeting is currently live and I can connect 
to SockJS endpoint to get list of participants and events when they leave.

If meeting is not live, then I do `GET /v1/user/{user_id}/scheduled_meeting/{meeting_id}`
to see if meeting is not started yet.

If meeting is not scheduled and not live, then its probably completed, so to 
get list of participants I do `GET /v1/enterprise/{enterprise_id}/indigo/meetings/{meeting_uuid}?includeEndpoints=true`

Questions:
1. Is there any easier way to do that? I need to know meeting's status and list of endpoints. 
2. `GET /v1/enterprise/{enterprise_id}/indigo/meetings/{meeting_uuid}?includeEndpoints=true` can take like 90 seconds to get a response, maybe I can use some params to make it faster, or there any other API method where I can get a list of patricipants (endpoints) for completed meeting?

**Comment by glenninn** [comment]
Hi,
  To determine the meeting state, I would try this:

1) Query to see if meeting is live
/v1/enterprise/{enterprise_id}/indigo/meetings/live  _(Live Meetings Summary by Enterprise)_
2) Query to see if meeting has passed
/v1/enterprise/{enterprise_id}/indigo/meetings  _(List Past Meetings by Enterprise)_

That leaves either the Meeting hasn't started, or wasn't scheduled.

Presumably if you are doing this search then the meeting must have been scheduled already - so that leaves, by induction, that the meeting hasn't started yet.

-Glenn
